name: Destroy Terraform Infrastructure

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repo
    - name: Checkout Code
      uses: actions/checkout@v3
    
    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.1 # Adjust to your Terraform version

    # Configure cloud credentials
    - name: Configure AWS Credentials
      if: ${{ secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your region

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan destroy (optional, for review before destroy)
    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfplan

    # Apply destroy
    - name: Terraform Destroy
      run: terraform apply -auto-approve -destroy
